M48
; DRILL file {KiCad 7.0.1} date Sun Dec  8 14:30:27 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-08T14:30:27-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.3325Y-3.0095
X4.5234Y-3.0095
T2
X4.3207Y-2.8902
X4.5352Y-2.8902
T0
M30
