M48
; DRILL file {KiCad (6.0.11)} date Thu Apr 11 16:40:27 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-11T16:40:27-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
%
G90
G05
T1
X6.1634Y-3.0335
X6.1634Y-3.3091
X6.6161Y-3.0335
X6.6161Y-3.3091
T0
M30
