M48
; DRILL file {KiCad (6.0.11)} date Mon Jan 15 12:10:10 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-15T12:10:10-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1378
%
G90
G05
T1
X3.0223Y-1.8524
X3.0223Y-2.128
T2
X9.1791Y-6.3799
X9.1791Y-7.3327
T3
X2.2717Y-3.9539
T0
M30
