CHIP "SAB80535-CPLD"
BEGIN

    DEVICE = "PLCC44";
    "TXxLED"                                  : OUTPUT_PIN = 4 ;
    "TxDx0"                                   : OUTPUT_PIN = 5 ;
    "OE"                                      : OUTPUT_PIN = 6 ;
    "TDI"                                     : INPUT_PIN = 7 ;
    "CSxLCD"                                  : OUTPUT_PIN = 8 ;
    "CSxP3"                                   : OUTPUT_PIN = 9 ;
    "CSxP1"                                   : OUTPUT_PIN = 11 ;
    "CSxP2"                                   : OUTPUT_PIN = 12 ;
    "TMS"                                     : INPUT_PIN = 13 ;
    "CSxP0"                                   : OUTPUT_PIN = 14 ;
    "CSxPPI1"                                 : OUTPUT_PIN = 16 ;
    "CSxPPI0"                                 : OUTPUT_PIN = 17 ;
    "RxD"                                     : OUTPUT_PIN = 18 ;
    "RXxLED"                                  : OUTPUT_PIN = 19 ;
    "CSxROM"                                  : OUTPUT_PIN = 20 ;
    "CSxLCDxWR"                               : OUTPUT_PIN = 21 ;
    "TO"                                      : INPUT_PIN = 41 ;
    "TxD"                                     : INPUT_PIN = 40 ;
    "A10"                                     : INPUT_PIN = 39 ;
    "TDO"                                     : INPUT_PIN = 38 ;
    "A11"                                     : INPUT_PIN = 37 ;
    "A12"                                     : INPUT_PIN = 36 ;
    "A13"                                     : INPUT_PIN = 34 ;
    "A14"                                     : INPUT_PIN = 33 ;
    "TCK"                                     : INPUT_PIN = 32 ;
    "A15"                                     : INPUT_PIN = 31 ;
    "A8"                                      : INPUT_PIN = 29 ;
    "A9"                                      : INPUT_PIN = 28 ;
    "RD"                                      : INPUT_PIN = 27 ;
    "WR"                                      : INPUT_PIN = 26 ;
    "TO1"                                     : OUTPUT_PIN = 25 ;
    "TxDx1"                                   : OUTPUT_PIN = 24 ;
    "PSEN"                                    : INPUT_PIN = 2 ;
    "RxDx1"                                   : INPUT_PIN = 43 ;
    "RxDx0"                                   : INPUT_PIN = 1 ;
END;
