#! /bin/sh
#
export ZSUF=tar.gz
export ZIP="tar cvfz"
export DRIVE=/media/jrc/BULLET8-1
export DIR=SBC188

echo "SAVE has control"   $1    $2    ..

if [ ! "$1" ]; then
	echo listing ...
	ls -l --color=always *.$ZSUF
	echo end of list
	echo "****************************************************"
	echo "**** DO NOT FORGET TO INSTALL THE BACKUP MEDIUM ****"
	echo "****************************************************"
	exit
fi
if [ -e "$1" ]; then
	echo "\"$1\"" already exists
	exit
fi
if [ -e "$1.$ZSUF" ]; then
	echo \"$1.$ZSUF\" already exists
	exit
fi

# convert all filenames to lower case
rename "y/A-Z/a-z/" *
# restore some names
rename "y/a-z/A-Z/" copying r_cini

$ZIP $1.$ZSUF COPYING save M* make* *.lib *.cfg *.asm *. *.inc *.b* e*.sys *.c *.h *.doc *.txt fpem/*.asm fpem/make* \
	unasm/* tools/* dmaide/*
echo Done Compression.

cp -v $1.$ZSUF $DRIVE/$DIR

echo Done Save.
exit
